### ISSUE TITLE
Proceso del TP

### ISSUE THREAD

**Issue by Nicodc96** [Nicodc96/TP_SO_I4_EQUIPO_9#1]

**Comment by carlospcalvo** [comment]
Somos el equipo 9 creo jajaj

**Comment by Nicodc96** [comment]
Ahí lo arreglé xd, pero van a tener que volver a clonar o cambiar el nombre a mano si ya lo tienen local

**Comment by carlospcalvo** [comment]
Listo el punto 4

**Comment by tomas28** [comment]
ok

**Comment by tomas28** [comment]
con el merg, que tiene que quedar en DESARROLLO
todo lo del master o solo el favicon?

**Comment by carlospcalvo** [comment]
vas a tener que agregar el favicon y el html con la modificación

**Comment by tomas28** [comment]
ok gracias

**Comment by Nicodc96** [comment]
El merge es llevar lo de testing a desarrollo

**Comment by tomas28** [comment]
no estoy estendiendo si tengo que mover lo de testing a desarrollo o dejar el html y el favicon en el desarrollo

**Comment by carlospcalvo** [comment]
una vez que pusiste el html con los cambios en testing y el favicon, tenés que mergear testing con desarrollo segun entiendo

**Comment by tomas28** [comment]
listo ahi esntendi

**Comment by tomas28** [comment]
este tp esta tomo mal hecho xd

**Comment by carlospcalvo** [comment]
no entiendo cual es el problema, pero como quieran, no hay drama

**Comment by tomas28** [comment]
hagamos esto, avisen por aca cuando terminen de hacer un punto y lo vamos haciendo asi, ya que no vamos a poder terminar ahora. No se que opinan ustedes

**Comment by tomas28** [comment]
total tenemos hasta la clase que viene inclusive

**Comment by Nicodc96** [comment]
No creo que terminemos ahora pero voy a tratar de arreglar las branch

**Comment by tomas28** [comment]
para mi empezalo otra vez con todo organizado

**Comment by tomas28** [comment]
hacerlo otra vez pero primero creando el index y el estilos, y despues crear las ramas

**Comment by Nicodc96** [comment]
Ahí ya lo arreglé para que todas las branch estén iguales. Seguro van a tener que eliminar los archivos locales y volver a hacer un clone. Y nada, de ahí seguir.

**Comment by tomas28** [comment]
joya

**Comment by carlospcalvo** [comment]
oka

**Comment by tomas28** [comment]
entonces ahora hay que hacer lo que hicimos otra vez no?

**Comment by Nicodc96** [comment]
Claro, descargan de manera local, y se vuelve al punto 4.

**Comment by carlospcalvo** [comment]
Arrancando el 4

**Comment by carlospcalvo** [comment]
Listo el 4!

**Comment by tomas28** [comment]
ahi arranco

**Comment by Nicodc96** [comment]
Cualquier cosa, fijate si podes hacer el 5, después cada uno actualiza su repositorio y la dejamos ahí.

**Comment by carlospcalvo** [comment]
Yo preferiría liquidarlo hoy, si no vamos a colgarlo

**Comment by carlospcalvo** [comment]
O cuanto antes

**Comment by tomas28** [comment]
yo no dormi todavia estoy bastante muerto xd

**Comment by tomas28** [comment]
me tiran una ayudita con el merge jeje

**Comment by Nicodc96** [comment]
Primero haces los cambios en testing, haces el commit y el push, y después haces el merge a desarrollo.

**Comment by tomas28** [comment]
los cambios ya los hice pero no se hacer el merge

**Comment by Nicodc96** [comment]
Te pones en el branch desarrollo y pones: 
git merge origin testing
Así debería funcionar al menos xd

**Comment by tomas28** [comment]
ahi purebo gracias

**Comment by tomas28** [comment]
listo el 5

**Comment by carlospcalvo** [comment]
Actualicé y tengo los cambios

**Comment by Nicodc96** [comment]
También, actualicé y tengo los cambios.

**Comment by tomas28** [comment]
ya cambie de color

**Comment by tomas28** [comment]
osea hice el 7 xd

**Comment by carlospcalvo** [comment]
dale, ahí hago el 8

**Comment by tomas28** [comment]
che yo me voy a dormir adelanten si quieren, el punto de que yo tengo que cambiar a color azul tranquilamente lo podemos saltear asi adelantan mas xd

**Comment by carlospcalvo** [comment]
Listo el 8

**Comment by Nicodc96** [comment]
Listo el 10, que tomas haga su parte cuando pueda, la onda sería terminarlo lo antes posible.

**Comment by tomas28** [comment]
les pido disculpas chicos, tuve problemas el finde para hacer mi parte y me olvide. ya hice el punto 12

**Comment by carlospcalvo** [comment]
Listo el 13, pero como no dice de hacer push no lo hice y por lo tanto nadie debería poder ver el cambio

**Comment by Nicodc96** [comment]
Es verdad, es raro eso, pero bueno, ahora hago el 15 y el 16

**Comment by Nicodc96** [comment]
Listo el 15 y el 16

**Comment by Nicodc96** [comment]
Ahí subí el .txt con las respuestas para que pongan su apellido y nombre

**Comment by carlospcalvo** [comment]
datos.txt está vacío, estilo.css tiene fondo azul , el favicon es el que yo (alfa) puse, y el index.html está como en la rama testing

**Comment by carlospcalvo** [comment]
Ahí respondí hasta la 4ta pregunta

**Comment by Nicodc96** [comment]
Genial, habría que hacer el 18,19,20 y 21 ahora y responder lo demás

**Comment by tomas28** [comment]
ya lo tengo modificado avisen cuando esten listos para hacer el push

**Comment by tomas28** [comment]
hay que actualizar antes de hacer el push?

**Comment by Nicodc96** [comment]
Claro tendrías que tener tu repositorio local actualizado y luego hacer lo del punto 19

**Comment by Nicodc96** [comment]
Hay que esperar que carlos haga su parte y diga cuando haga el push

**Comment by carlospcalvo** [comment]
Pongamos una hora exacta para hacer los push así se hacen al mismo momento, ya tengo todo listo

**Comment by carlospcalvo** [comment]
no dije nada, leí la consigna y tengo que hacer push yo primero, ya lo hice

**Comment by tomas28** [comment]
ok

**Comment by tomas28** [comment]
listo el push

**Comment by tomas28** [comment]
e- no hubo problemas
f- no surgieron problemas

**Comment by Nicodc96** [comment]
Ahí respondí con un problema que tuve yo, si alguno quiere agregar algo, hágalo nomás

**Comment by carlospcalvo** [comment]
hay que probar el push -f, le mando

**Comment by carlospcalvo** [comment]
para no modificar nada groso agreguenle un comentario al index.html con el tag

**Comment by Nicodc96** [comment]
¿Vos decís agregar otro <p> para probar?

**Comment by tomas28** [comment]
nico como hiciste los puntos 15 y 16 
si podes pasame los comandos , porq a un amigo no le sale y esta trabado en eso

**Comment by Nicodc96** [comment]
Se tiene que parar donde quiere hacer el merge (es decir, si quiere hacer un merge de desarrollo a master, se tiene que parar en master) y hacer el 'git merge origin/desarrollo' y después el push

**Comment by tomas28** [comment]
gracias

**Comment by Nicodc96** [comment]
Falta poner tu nombre y apellido en las respuestas tomas

**Comment by tomas28** [comment]
no me habia dado cuenta gracias

**Comment by Nicodc96** [comment]
Creo que ya estamos.

**Comment by tomas28** [comment]
genial
